{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This Python 3 environment comes with many helpful analytics libraries installed\n",
    "# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python\n",
    "# For example, here's several helpful packages to load in \n",
    "\n",
    "import numpy as np # linear algebra\n",
    "import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n",
    "\n",
    "# Input data files are available in the \"../input/\" directory.\n",
    "# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory\n",
    "\n",
    "import os\n",
    "\n",
    "\n",
    "# Any results you write to the current directory are saved as output."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>PassengerId</th>\n",
       "      <th>Survived</th>\n",
       "      <th>Pclass</th>\n",
       "      <th>Name</th>\n",
       "      <th>Sex</th>\n",
       "      <th>Age</th>\n",
       "      <th>SibSp</th>\n",
       "      <th>Parch</th>\n",
       "      <th>Ticket</th>\n",
       "      <th>Fare</th>\n",
       "      <th>Cabin</th>\n",
       "      <th>Embarked</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>307</th>\n",
       "      <td>308</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Penasco y Castellana, Mrs. Victor de Satode (M...</td>\n",
       "      <td>female</td>\n",
       "      <td>17.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>PC 17758</td>\n",
       "      <td>108.9000</td>\n",
       "      <td>C65</td>\n",
       "      <td>C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>510</th>\n",
       "      <td>511</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>Daly, Mr. Eugene Patrick</td>\n",
       "      <td>male</td>\n",
       "      <td>29.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>382651</td>\n",
       "      <td>7.7500</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Q</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>200</th>\n",
       "      <td>201</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>Vande Walle, Mr. Nestor Cyriel</td>\n",
       "      <td>male</td>\n",
       "      <td>28.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>345770</td>\n",
       "      <td>9.5000</td>\n",
       "      <td>NaN</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>533</th>\n",
       "      <td>534</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>Peter, Mrs. Catherine (Catherine Rizk)</td>\n",
       "      <td>female</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>2668</td>\n",
       "      <td>22.3583</td>\n",
       "      <td>NaN</td>\n",
       "      <td>C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>649</th>\n",
       "      <td>650</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>Stanley, Miss. Amy Zillah Elsie</td>\n",
       "      <td>female</td>\n",
       "      <td>23.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>CA. 2314</td>\n",
       "      <td>7.5500</td>\n",
       "      <td>NaN</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>623</th>\n",
       "      <td>624</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>Hansen, Mr. Henry Damsgaard</td>\n",
       "      <td>male</td>\n",
       "      <td>21.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>350029</td>\n",
       "      <td>7.8542</td>\n",
       "      <td>NaN</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>279</th>\n",
       "      <td>280</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>Abbott, Mrs. Stanton (Rosa Hunt)</td>\n",
       "      <td>female</td>\n",
       "      <td>35.0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>C.A. 2673</td>\n",
       "      <td>20.2500</td>\n",
       "      <td>NaN</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>824</th>\n",
       "      <td>825</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>Panula, Master. Urho Abraham</td>\n",
       "      <td>male</td>\n",
       "      <td>2.0</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>3101295</td>\n",
       "      <td>39.6875</td>\n",
       "      <td>NaN</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>656</th>\n",
       "      <td>657</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>Radeff, Mr. Alexander</td>\n",
       "      <td>male</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>349223</td>\n",
       "      <td>7.8958</td>\n",
       "      <td>NaN</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>402</th>\n",
       "      <td>403</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>Jussila, Miss. Mari Aina</td>\n",
       "      <td>female</td>\n",
       "      <td>21.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>4137</td>\n",
       "      <td>9.8250</td>\n",
       "      <td>NaN</td>\n",
       "      <td>S</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     PassengerId  Survived  Pclass  \\\n",
       "307          308         1       1   \n",
       "510          511         1       3   \n",
       "200          201         0       3   \n",
       "533          534         1       3   \n",
       "649          650         1       3   \n",
       "623          624         0       3   \n",
       "279          280         1       3   \n",
       "824          825         0       3   \n",
       "656          657         0       3   \n",
       "402          403         0       3   \n",
       "\n",
       "                                                  Name     Sex   Age  SibSp  \\\n",
       "307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0      1   \n",
       "510                           Daly, Mr. Eugene Patrick    male  29.0      0   \n",
       "200                     Vande Walle, Mr. Nestor Cyriel    male  28.0      0   \n",
       "533             Peter, Mrs. Catherine (Catherine Rizk)  female   NaN      0   \n",
       "649                    Stanley, Miss. Amy Zillah Elsie  female  23.0      0   \n",
       "623                        Hansen, Mr. Henry Damsgaard    male  21.0      0   \n",
       "279                   Abbott, Mrs. Stanton (Rosa Hunt)  female  35.0      1   \n",
       "824                       Panula, Master. Urho Abraham    male   2.0      4   \n",
       "656                              Radeff, Mr. Alexander    male   NaN      0   \n",
       "402                           Jussila, Miss. Mari Aina  female  21.0      1   \n",
       "\n",
       "     Parch     Ticket      Fare Cabin Embarked  \n",
       "307      0   PC 17758  108.9000   C65        C  \n",
       "510      0     382651    7.7500   NaN        Q  \n",
       "200      0     345770    9.5000   NaN        S  \n",
       "533      2       2668   22.3583   NaN        C  \n",
       "649      0   CA. 2314    7.5500   NaN        S  \n",
       "623      0     350029    7.8542   NaN        S  \n",
       "279      1  C.A. 2673   20.2500   NaN        S  \n",
       "824      1    3101295   39.6875   NaN        S  \n",
       "656      0     349223    7.8958   NaN        S  \n",
       "402      0       4137    9.8250   NaN        S  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "input_dir = '../data/'\n",
    "\n",
    "train_csv = pd.read_csv(input_dir + 'train.csv')\n",
    "train_csv.sample(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "PassengerId    891\n",
       "Survived         2\n",
       "Pclass           3\n",
       "Name           891\n",
       "Sex              2\n",
       "Age             89\n",
       "SibSp            7\n",
       "Parch            7\n",
       "Ticket         681\n",
       "Fare           248\n",
       "Cabin          148\n",
       "Embarked         4\n",
       "dtype: int64"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unique_count_df = pd.Series()\n",
    "for col in train_csv.columns:\n",
    "    unique_count_df[col] = len(train_csv[col].unique())\n",
    "unique_count_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def split_data(df: pd.DataFrame):\n",
    "    df_shuffled = df.sample(frac=1).reset_index(drop=True)\n",
    "    num_rows = df.shape[0]\n",
    "    num_rows_train_data = int(num_rows * 0.8)\n",
    "\n",
    "    train_data = df_shuffled[:num_rows_train_data]\n",
    "    val_data = df_shuffled[num_rows_train_data:]\n",
    "    \n",
    "    return (train_data, val_data)\n",
    "\n",
    "def input_fn(df: pd.DataFrame, labels, batch_size: int, num_epochs: int):\n",
    "    if labels is None:\n",
    "        input = df.to_dict(orient='series')\n",
    "    else:\n",
    "        input = (df.to_dict(orient='series'), labels)\n",
    "    dataset = tf.data.Dataset.from_tensor_slices(input)\n",
    "    return dataset.shuffle(buffer_size=10000).repeat(count=num_epochs).batch(batch_size)\n",
    "\n",
    "def eval_input_fn(df: pd.DataFrame, labels):\n",
    "    if labels is None:\n",
    "        input = df.to_dict(orient='series')\n",
    "    else:\n",
    "        input = (df.to_dict(orient='series'), labels)\n",
    "    dataset = tf.data.Dataset.from_tensor_slices(input)\n",
    "    return dataset.batch(128)\n",
    "\n",
    "def embedding_dimension(unique_count):\n",
    "    return min(50, unique_count // 2)\n",
    "\n",
    "def define_feature_columns(df: pd.DataFrame, numeric_columns, categorical_columns):\n",
    "    feature_columns = []\n",
    "    for col in df.columns:\n",
    "        if col in categorical_columns:\n",
    "            sorted_unique_values = sorted(set(list(df[col].unique()) + ['']))\n",
    "            cat_col = tf.feature_column.categorical_column_with_vocabulary_list(key=col, vocabulary_list=sorted_unique_values)\n",
    "            embedding_dim = embedding_dimension(len(sorted_unique_values))\n",
    "            if embedding_dim <= 2:\n",
    "                feature_columns.append((col, tf.feature_column.indicator_column(cat_col)))\n",
    "            else:\n",
    "                feature_columns.append((col, tf.feature_column.embedding_column(cat_col, embedding_dim)))\n",
    "        elif col in numeric_columns:\n",
    "            feature_columns.append((col, tf.feature_column.numeric_column(key=col)))\n",
    "            isnull_col_name = col + 'IsNull'\n",
    "            feature_columns.append((isnull_col_name, tf.feature_column.numeric_column(key=isnull_col_name)))\n",
    "    return dict(feature_columns)\n",
    "\n",
    "def feature_preprocess(df: pd.DataFrame, numeric_columns, categorical_columns, col_mean, col_stddev):\n",
    "    processed = pd.DataFrame()\n",
    "    processed['PassengerId'] = df['PassengerId']\n",
    "    \n",
    "    for col_name in numeric_columns:\n",
    "        processed[col_name] = (df[col_name].astype(float) - col_mean[col_name]) / col_stddev[col_name]\n",
    "        isnull_col_name = col_name + 'IsNull'\n",
    "        processed[isnull_col_name] = df[col_name].isnull()\n",
    "        processed.loc[processed[isnull_col_name], col_name] = 0\n",
    "        processed[isnull_col_name] = processed[isnull_col_name].astype(np.int8)\n",
    "        \n",
    "    for col_name in categorical_columns:\n",
    "        processed[col_name] = df[col_name].copy().astype(str)\n",
    "        processed.loc[df[col_name].isnull(), col_name] = ''\n",
    "    \n",
    "    return processed"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(712, 13) (179, 13)\n"
     ]
    }
   ],
   "source": [
    "input_dir = '../data/'\n",
    "\n",
    "train_csv = pd.read_csv(input_dir + 'train.csv')\n",
    "test_csv = pd.read_csv(input_dir + 'test.csv')\n",
    "\n",
    "train_csv['Deck'] = train_csv['Cabin'].str[0]\n",
    "test_csv['Deck'] = test_csv['Cabin'].str[0]\n",
    "\n",
    "train_data, val_data = split_data(train_csv)\n",
    "print(train_data.shape, val_data.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   PassengerId       Age  AgeIsNull     SibSp  SibSpIsNull     Parch  \\\n",
      "0           83  0.000000          1 -0.466103            0 -0.476682   \n",
      "1          204  1.063727          0 -0.466103            0 -0.476682   \n",
      "2          775  1.647992          0  0.404934            0  3.225839   \n",
      "3          738  0.341988          0 -0.466103            0 -0.476682   \n",
      "4          414  0.000000          1 -0.466103            0 -0.476682   \n",
      "\n",
      "   ParchIsNull      Fare  FareIsNull Pclass     Sex    Ticket Cabin Embarked  \\\n",
      "0            0 -0.483357           0      3  female    330932              Q   \n",
      "1            0 -0.494085           0      3    male      2628              C   \n",
      "2            0 -0.193224           0      2  female     29105              S   \n",
      "3            0  9.139273           0      1    male  PC 17755  B101        C   \n",
      "4            0 -0.631880           0      2    male    239853              S   \n",
      "\n",
      "  Deck  \n",
      "0       \n",
      "1       \n",
      "2       \n",
      "3    B  \n",
      "4       \n",
      "INFO:tensorflow:Using default config.\n",
      "WARNING:tensorflow:Using temporary folder as model directory: C:\\Users\\HPE\\AppData\\Local\\Temp\\tmpdlymsfc4\n",
      "INFO:tensorflow:Using config: {'_model_dir': 'C:\\\\Users\\\\HPE\\\\AppData\\\\Local\\\\Temp\\\\tmpdlymsfc4', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true\n",
      "graph_options {\n",
      "  rewrite_options {\n",
      "    meta_optimizer_iterations: ONE\n",
      "  }\n",
      "}\n",
      ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001F0BC735C18>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n"
     ]
    }
   ],
   "source": [
    "numeric_columns = ['Age', 'SibSp', 'Parch', 'Fare']\n",
    "categorical_columns = ['Pclass', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'Deck']\n",
    "\n",
    "col_mean = train_data[numeric_columns].mean()\n",
    "col_stddev = train_data[numeric_columns].std()\n",
    "\n",
    "def feature_preprocess_1(df: pd.DataFrame):\n",
    "    return feature_preprocess(df, numeric_columns=numeric_columns, categorical_columns=categorical_columns, col_mean=col_mean, col_stddev=col_stddev)\n",
    "\n",
    "train_features = feature_preprocess_1(train_data)\n",
    "val_features = feature_preprocess_1(val_data)\n",
    "\n",
    "print(train_features.head())\n",
    "\n",
    "feature_columns = define_feature_columns(\n",
    "    train_features,\n",
    "    numeric_columns=numeric_columns,\n",
    "    categorical_columns=categorical_columns)\n",
    "\n",
    "classifier = tf.estimator.DNNClassifier(\n",
    "    feature_columns=list(feature_columns.values()),\n",
    "    hidden_units=[64, 32, 16],\n",
    "    n_classes=2,\n",
    "    dropout=0.5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "WARNING:tensorflow:From C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0BC7EB748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0BC7EB748>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0BC7EB748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0BC7EB748>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING:tensorflow:From C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\feature_column\\feature_column_v2.py:3038: VocabularyListCategoricalColumn._num_buckets (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.\n",
      "WARNING:tensorflow:Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0BC740A58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0BC740A58>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0BC740A58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0BC740A58>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING:tensorflow:From C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\feature_column\\feature_column_v2.py:2655: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.where in 2.0, which has the same broadcast rule as np.where\n",
      "WARNING:tensorflow:From C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\feature_column\\feature_column_v2.py:4207: IndicatorColumn._variable_shape (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF7B8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF7B8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF7B8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF7B8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC7DF470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC7DF470>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC7DF470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC7DF470>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF668>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF668>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC7DF4E0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC7DF4E0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC7DF4E0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC7DF4E0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF5C0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF5C0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF5C0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC7DF5C0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC8265C0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC8265C0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC8265C0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x000001F0BC8265C0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC826668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC826668>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC826668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BC826668>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:From C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\canned\\head.py:437: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.cast` instead.\n",
      "WARNING:tensorflow:From C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\adagrad.py:76: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into C:\\Users\\HPE\\AppData\\Local\\Temp\\tmpdlymsfc4\\model.ckpt.\n",
      "INFO:tensorflow:loss = 45.10874, step = 1\n",
      "INFO:tensorflow:global_step/sec: 299.168\n",
      "INFO:tensorflow:loss = 2.2042937, step = 101 (0.335 sec)\n",
      "INFO:tensorflow:global_step/sec: 593.298\n",
      "INFO:tensorflow:loss = 4.243692, step = 201 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 600.404\n",
      "INFO:tensorflow:loss = 0.4422749, step = 301 (0.167 sec)\n",
      "INFO:tensorflow:global_step/sec: 604.02\n",
      "INFO:tensorflow:loss = 0.60483193, step = 401 (0.166 sec)\n",
      "INFO:tensorflow:global_step/sec: 596.831\n",
      "INFO:tensorflow:loss = 0.6782328, step = 501 (0.168 sec)\n",
      "INFO:tensorflow:global_step/sec: 589.718\n",
      "INFO:tensorflow:loss = 0.049510326, step = 601 (0.170 sec)\n",
      "INFO:tensorflow:global_step/sec: 600.497\n",
      "INFO:tensorflow:loss = 0.25088692, step = 701 (0.168 sec)\n",
      "INFO:tensorflow:global_step/sec: 601.212\n",
      "INFO:tensorflow:loss = 0.18193202, step = 801 (0.165 sec)\n",
      "INFO:tensorflow:global_step/sec: 603.261\n",
      "INFO:tensorflow:loss = 0.23868205, step = 901 (0.166 sec)\n",
      "INFO:tensorflow:global_step/sec: 593.302\n",
      "INFO:tensorflow:loss = 0.77966195, step = 1001 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 593.298\n",
      "INFO:tensorflow:loss = 0.31269225, step = 1101 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 596.83\n",
      "INFO:tensorflow:loss = 0.07899483, step = 1201 (0.168 sec)\n",
      "INFO:tensorflow:global_step/sec: 596.831\n",
      "INFO:tensorflow:loss = 0.0017815116, step = 1301 (0.168 sec)\n",
      "INFO:tensorflow:global_step/sec: 593.297\n",
      "INFO:tensorflow:loss = 0.722631, step = 1401 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 665.036\n",
      "INFO:tensorflow:loss = 0.17819779, step = 1501 (0.165 sec)\n",
      "INFO:tensorflow:global_step/sec: 544.816\n",
      "INFO:tensorflow:loss = 1.0733719, step = 1601 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 593.298\n",
      "INFO:tensorflow:loss = 0.7590022, step = 1701 (0.170 sec)\n",
      "INFO:tensorflow:global_step/sec: 593.299\n",
      "INFO:tensorflow:loss = 0.39914897, step = 1801 (0.168 sec)\n",
      "INFO:tensorflow:global_step/sec: 615.451\n",
      "INFO:tensorflow:loss = 0.0011402303, step = 1901 (0.161 sec)\n",
      "INFO:tensorflow:global_step/sec: 652.746\n",
      "INFO:tensorflow:loss = 0.19553931, step = 2001 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 545.327\n",
      "INFO:tensorflow:loss = 0.00010924664, step = 2101 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 596.832\n",
      "INFO:tensorflow:loss = 0.07048808, step = 2201 (0.168 sec)\n",
      "INFO:tensorflow:global_step/sec: 589.808\n",
      "INFO:tensorflow:loss = 0.6191146, step = 2301 (0.170 sec)\n",
      "INFO:tensorflow:global_step/sec: 596.831\n",
      "INFO:tensorflow:loss = 8.239943e-05, step = 2401 (0.168 sec)\n",
      "INFO:tensorflow:global_step/sec: 593.297\n",
      "INFO:tensorflow:loss = 0.6710971, step = 2501 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 596.83\n",
      "INFO:tensorflow:loss = 0.021139652, step = 2601 (0.168 sec)\n",
      "INFO:tensorflow:global_step/sec: 589.809\n",
      "INFO:tensorflow:loss = 0.6129608, step = 2701 (0.170 sec)\n",
      "INFO:tensorflow:global_step/sec: 592.444\n",
      "INFO:tensorflow:loss = 0.025274804, step = 2801 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 593.299\n",
      "INFO:tensorflow:loss = 0.479123, step = 2901 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 586.355\n",
      "INFO:tensorflow:loss = 4.097531, step = 3001 (0.171 sec)\n",
      "INFO:tensorflow:global_step/sec: 593.301\n",
      "INFO:tensorflow:loss = 1.4057859, step = 3101 (0.169 sec)\n",
      "INFO:tensorflow:global_step/sec: 626.225\n",
      "INFO:tensorflow:loss = 1.5537415, step = 3201 (0.159 sec)\n",
      "INFO:tensorflow:global_step/sec: 599.469\n",
      "INFO:tensorflow:loss = 0.7061252, step = 3301 (0.167 sec)\n",
      "INFO:tensorflow:global_step/sec: 586.557\n",
      "INFO:tensorflow:loss = 0.1003137, step = 3401 (0.171 sec)\n",
      "INFO:tensorflow:global_step/sec: 680.02\n",
      "INFO:tensorflow:loss = 0.85102546, step = 3501 (0.146 sec)\n",
      "INFO:tensorflow:global_step/sec: 574.077\n",
      "INFO:tensorflow:loss = 0.7211835, step = 3601 (0.175 sec)\n",
      "INFO:tensorflow:global_step/sec: 622.882\n",
      "INFO:tensorflow:loss = 0.00049353094, step = 3701 (0.161 sec)\n",
      "INFO:tensorflow:global_step/sec: 622.365\n",
      "INFO:tensorflow:loss = 0.6043998, step = 3801 (0.161 sec)\n",
      "INFO:tensorflow:global_step/sec: 600.403\n",
      "INFO:tensorflow:loss = 0.85982364, step = 3901 (0.167 sec)\n",
      "INFO:tensorflow:global_step/sec: 607.683\n",
      "INFO:tensorflow:loss = 0.97375077, step = 4001 (0.165 sec)\n",
      "INFO:tensorflow:global_step/sec: 620.621\n",
      "INFO:tensorflow:loss = 0.5620854, step = 4101 (0.161 sec)\n",
      "INFO:tensorflow:global_step/sec: 694.49\n",
      "INFO:tensorflow:loss = 0.012635997, step = 4201 (0.143 sec)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:global_step/sec: 544.414\n",
      "INFO:tensorflow:loss = 2.2616625, step = 4301 (0.185 sec)\n",
      "INFO:tensorflow:global_step/sec: 600.401\n",
      "INFO:tensorflow:loss = 0.63568264, step = 4401 (0.167 sec)\n",
      "INFO:tensorflow:global_step/sec: 600.408\n",
      "INFO:tensorflow:loss = 1.1261826, step = 4501 (0.167 sec)\n",
      "INFO:tensorflow:global_step/sec: 600.403\n",
      "INFO:tensorflow:loss = 8.074184e-05, step = 4601 (0.167 sec)\n",
      "INFO:tensorflow:global_step/sec: 661.598\n",
      "INFO:tensorflow:loss = 7.696128e-07, step = 4701 (0.150 sec)\n",
      "INFO:tensorflow:global_step/sec: 582.955\n",
      "INFO:tensorflow:loss = 0.007832676, step = 4801 (0.174 sec)\n",
      "INFO:tensorflow:global_step/sec: 681.22\n",
      "INFO:tensorflow:loss = 0.6298303, step = 4901 (0.145 sec)\n",
      "INFO:tensorflow:global_step/sec: 579.001\n",
      "INFO:tensorflow:loss = 0.18783337, step = 5001 (0.174 sec)\n",
      "INFO:tensorflow:global_step/sec: 631.931\n",
      "INFO:tensorflow:loss = 1.0813136, step = 5101 (0.158 sec)\n",
      "INFO:tensorflow:global_step/sec: 621.337\n",
      "INFO:tensorflow:loss = 1.4457684, step = 5201 (0.160 sec)\n",
      "INFO:tensorflow:global_step/sec: 626.671\n",
      "INFO:tensorflow:loss = 0.0007516035, step = 5301 (0.161 sec)\n",
      "INFO:tensorflow:global_step/sec: 626.675\n",
      "INFO:tensorflow:loss = 0.05817208, step = 5401 (0.160 sec)\n",
      "INFO:tensorflow:global_step/sec: 629.409\n",
      "INFO:tensorflow:loss = 1.6074216, step = 5501 (0.159 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5563 into C:\\Users\\HPE\\AppData\\Local\\Temp\\tmpdlymsfc4\\model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0009809922.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<tensorflow_estimator.python.estimator.canned.dnn.DNNClassifier at 0x1f0b6f7ae48>"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "classifier.train(input_fn=lambda: input_fn(train_features, train_data['Survived'], batch_size=64, num_epochs=500))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Calling model_fn.\n",
      "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0B728E6D8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0B728E6D8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0B728E6D8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0B728E6D8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING:tensorflow:Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0C1104EF0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0C1104EF0>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0C1104EF0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0C1104EF0>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C11096A0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C11096A0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C11096A0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C11096A0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C1109438>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C1109438>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C1109438>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C1109438>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C1109160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C1109160>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C1109160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C1109160>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C112B208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C112B208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C112B208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0C112B208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:From C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\metrics_impl.py:2027: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Deprecated in favor of operator or tf.math.divide.\n",
      "WARNING:tensorflow:Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to \"careful_interpolation\" instead.\n",
      "WARNING:tensorflow:Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to \"careful_interpolation\" instead.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2019-09-24T08:38:53Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "WARNING:tensorflow:From C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use standard file APIs to check for files with this prefix.\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\HPE\\AppData\\Local\\Temp\\tmpdlymsfc4\\model.ckpt-5563\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Finished evaluation at 2019-09-24-08:38:54\n",
      "INFO:tensorflow:Saving dict for global step 5563: accuracy = 0.7821229, accuracy_baseline = 0.59217876, auc = 0.79329276, auc_precision_recall = 0.79888445, average_loss = 5.063408, global_step = 5563, label/mean = 0.40782124, loss = 453.175, precision = 0.7297297, prediction/mean = 0.41330647, recall = 0.739726\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 5563: C:\\Users\\HPE\\AppData\\Local\\Temp\\tmpdlymsfc4\\model.ckpt-5563\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'accuracy': 0.7821229,\n",
       " 'accuracy_baseline': 0.59217876,\n",
       " 'auc': 0.79329276,\n",
       " 'auc_precision_recall': 0.79888445,\n",
       " 'average_loss': 5.063408,\n",
       " 'label/mean': 0.40782124,\n",
       " 'loss': 453.175,\n",
       " 'precision': 0.7297297,\n",
       " 'prediction/mean': 0.41330647,\n",
       " 'recall': 0.739726,\n",
       " 'global_step': 5563}"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "classifier.evaluate(input_fn=lambda: eval_input_fn(val_features, val_data['Survived']))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Calling model_fn.\n",
      "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0BCD50D68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0BCD50D68>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0BCD50D68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000001F0BCD50D68>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING:tensorflow:Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0BCD50BA8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0BCD50BA8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0BCD50BA8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000001F0BCD50BA8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48AC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48AC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48AC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48AC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48710>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48710>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48240>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48240>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48240>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE48240>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE471D0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE471D0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE471D0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000001F0BCE471D0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from C:\\Users\\HPE\\AppData\\Local\\Temp\\tmpdlymsfc4\\model.ckpt-5563\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n"
     ]
    }
   ],
   "source": [
    "submit_data = feature_preprocess_1(test_csv)\n",
    "\n",
    "predictions = classifier.predict(input_fn=lambda: eval_input_fn(submit_data, None))\n",
    "predictions = list(predictions)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "pred = [x['class_ids'][0] for x in predictions]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_tmp =  pd.read_csv('../data/test.csv')\n",
    "X_tmp['Survived'] = pred\n",
    "sub = X_tmp[['PassengerId', 'Survived']]\n",
    "sub.head()\n",
    "sub.to_csv('submissionDNNC.csv', index = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
